server:
  port: 8080
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: myalias

openApi:
  appId:
  secret:
openai:
  secret_key:
volc:
  secret_key:
  access_key:
  ep_id:
spark:
  secret_key:
  api_key:
hunyuan:
  secret_id:
  secret_key:
zhipu:
  api_key:
qwen:
  api_key:
deepseek:
  secret_key:
novel:
  sourceId: 0
  extName: txt
  minInterval: 100
  maxInterval: 300
  threads: -1
    # 最大重试次数 (针对首次下载失败的章节)
  maxRetryAttempts: 3
    # 重试爬取最小间隔 (毫秒)
  retryMinInterval: 500
    # 重试爬取最大间隔 (毫秒)
  retryMaxInterval: 2000
